Parameters:
  Prefix:
    Type: String
    Description: "To avoid name collisions, resources are prefixed with this value"

  ImageUri:
    Type: String
    Description: ECS tasks should pull this docker image

Resources:
  LandingBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${Prefix}-landing-bucket
      
Outputs:
  LandingBucketRef:
    Value: !Ref LandingBucket
    Export:
      Name: !Sub ${Prefix}-S3-LandingBucket