from enum import Enum


class NODETYPE(Enum):
    SOMA = 1
    AXON = 2
    BASAL_DENDRITE = 3
    APICAL_DENDRITE = 4
    CUT_DENDRITE = 10
    NO_RECONSTRUCTION = 20
    TYPE_30 = 30


# For backwards compatability TODO: remove
SOMA = NODETYPE.SOMA.value
AXON = NODETYPE.AXON.value
BASAL_DENDRITE = NODETYPE.BASAL_DENDRITE.value
APICAL_DENDRITE = NODETYPE.APICAL_DENDRITE.value
CUT_DENDRITE = NODETYPE.CUT_DENDRITE.value
NO_RECONSTRUCTION = NODETYPE.NO_RECONSTRUCTION.value
TYPE_30 = NODETYPE.TYPE_30.value


# Other Constants
SPACING = [.1144, .1144, .28]
