FROM continuumio/miniconda3

RUN apt-get install -y libhdf5-dev

RUN conda create --name py38 python=3.8 -y

RUN activate py38 && \
    conda install -y -c conda-forge fenics mshr

RUN conda clean -ayv && \
    find /opt/conda -follow -type f -regex '*\.(a)|(pyc)' -delete
